// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace BasicFunctions
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// ClickingOn_browserPopup
        /// </summary>
        public void ClickingOn_browserPopup()
        {
            #region Variable Declarations
            HtmlDiv uINetBankingNetBankingPane = this.UIHDFCBankPersonalBankWindow.UIHDFCBankPersonalBankDocument.UIElement2Pane.UINetBankingNetBankingPane;
            HtmlHyperlink uILoginHyperlink = this.UIHDFCBankPersonalBankWindow.UIHDFCBankPersonalBankDocument.UILoginHyperlink;
            HtmlImage uIAssetspopuppagesimagImage = this.UINetBankingInternetExWindow.UINetBankingDocument.UISlide1Pane.UIAssetspopuppagesimagImage;
            HtmlDiv uIContinuetoNetBankingPane = this.UINetBankingInternetExWindow.UINetBankingDocument.UIContinuetoNetBankingPane;
            HtmlHyperlink uIContinuetoNetBankingHyperlink = this.UINetBankingInternetExWindow.UINetBankingDocument.UIContinuetoNetBankingHyperlink;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'NetBanking NetBanking Prepaid/ Forex' pane at (1, 1)
            Mouse.Hover(uINetBankingNetBankingPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Login' link
            Mouse.Click(uILoginHyperlink, new Point(58, 20));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover '/assets/popuppages/images/banner_4_desktop.jpg' image at (1, 1)
            Mouse.Hover(uIAssetspopuppagesimagImage, new Point(1, 1));

            // Mouse hover 'Continue to NetBanking' pane at (1, 1)
            Mouse.Hover(uIContinuetoNetBankingPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Continue to NetBanking' link
            Mouse.Click(uIContinuetoNetBankingHyperlink, new Point(104, 14));
        }
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            BrowserWindow uIHDFCBankPersonalBankWindow = this.UIHDFCBankPersonalBankWindow;
            HtmlImage uICloseImage = this.UIHDFCBankPersonalBankWindow.UIHDFCBankPersonalBankDocument.UICee_closeBtnPane.UICloseImage;
            HtmlDiv uIItemPane = this.UIHDFCBankPersonalBankWindow.UIHDFCBankPersonalBankDocument.UIElement2Pane.UIItemPane;
            HtmlHyperlink uILoginHyperlink1 = this.UIHDFCBankPersonalBankWindow.UIHDFCBankPersonalBankDocument.UILoginHyperlink1;
            HtmlImage uIAssetspopuppagesimagImage = this.UINetBankingInternetExWindow.UINetBankingDocument.UISlide1Pane.UIAssetspopuppagesimagImage;
            HtmlHyperlink uIContinuetoNetBankingHyperlink = this.UINetBankingInternetExWindow.UINetBankingDocument.UIContinuetoNetBankingHyperlink;
            #endregion

            // Go to web page 'https://www.hdfcbank.com/'
            uIHDFCBankPersonalBankWindow.NavigateToUrl(new System.Uri(this.RecordedMethod1Params.UIHDFCBankPersonalBankWindowUrl));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Close' image at (1, 1)
            Mouse.Hover(uICloseImage, new Point(1, 1));

            // Mouse hover  pane at (1, 1)
            Mouse.Hover(uIItemPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Close' image
            Mouse.Click(uICloseImage, new Point(25, 18));

            // Click 'Login' link
            Mouse.Click(uILoginHyperlink1, new Point(23, 15));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover '/assets/popuppages/images/banner_4_desktop.jpg' image at (1, 1)
            Mouse.Hover(uIAssetspopuppagesimagImage, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Continue to NetBanking' link
            Mouse.Click(uIContinuetoNetBankingHyperlink, new Point(201, 12));
        }
        
        /// <summary>
        /// RecordedMethod2 - Use 'RecordedMethod2Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            BrowserWindow uIHDFCBankPersonalBankWindow = this.UIHDFCBankPersonalBankWindow;
            HtmlImage uICloseImage = this.UIHDFCBankPersonalBankWindow.UIHDFCBankPersonalBankDocument.UICee_closeBtnPane.UICloseImage;
            HtmlDiv uIItemPane = this.UIHDFCBankPersonalBankWindow.UIHDFCBankPersonalBankDocument.UIElement2Pane.UIItemPane;
            HtmlHyperlink uILoginHyperlink1 = this.UIHDFCBankPersonalBankWindow.UIHDFCBankPersonalBankDocument.UILoginHyperlink1;
            HtmlImage uIAssetspopuppagesimagImage = this.UINetBankingInternetExWindow.UINetBankingDocument.UISlide1Pane.UIAssetspopuppagesimagImage;
            HtmlHyperlink uIContinuetoNetBankingHyperlink = this.UINetBankingInternetExWindow.UINetBankingDocument.UIContinuetoNetBankingHyperlink;
            HtmlDiv uIPreloaderPane = this.UINetBankingInternetExWindow.UINetBankingDocument.UIPreloaderPane;
            HtmlImage uISspIN_HDFC_DMP7f721cImage = this.UIHDFCBankPersonalBankWindow.UIHDFCBankPersonalBankDocument.UIViz_iframe36255a186aFrame.UITemplate_Fadein_FadeDocument.UIApplyNowPane.UISspIN_HDFC_DMP7f721cImage;
            #endregion

            // Go to web page 'https://www.hdfcbank.com/'
            uIHDFCBankPersonalBankWindow.NavigateToUrl(new System.Uri(this.RecordedMethod2Params.UIHDFCBankPersonalBankWindowUrl));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Close' image at (1, 1)
            Mouse.Hover(uICloseImage, new Point(1, 1));

            // Mouse hover  pane at (1, 1)
            Mouse.Hover(uIItemPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Close' image
            Mouse.Click(uICloseImage, new Point(25, 18));

            // Click 'Login' link
            Mouse.Click(uILoginHyperlink1, new Point(23, 15));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover '/assets/popuppages/images/banner_4_desktop.jpg' image at (1, 1)
            Mouse.Hover(uIAssetspopuppagesimagImage, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Continue to NetBanking' link
            Mouse.Click(uIContinuetoNetBankingHyperlink, new Point(201, 12));

            // Click 'Login' link
            Mouse.Click(uILoginHyperlink1, new Point(34, 15));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'preloader' pane at (1, 1)
            Mouse.Hover(uIPreloaderPane, new Point(1, 1));

            // Mouse hover '/assets/popuppages/images/banner_4_desktop.jpg' image at (1, 1)
            Mouse.Hover(uIAssetspopuppagesimagImage, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Continue to NetBanking' link
            Mouse.Click(uIContinuetoNetBankingHyperlink, new Point(178, 17));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover '/ssp/IN_HDFC_DMP/7f721c89-42b5-4d90-8c5e-116d98b95...' image at (1, 1)
            Mouse.Hover(uISspIN_HDFC_DMP7f721cImage, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Continue to NetBanking' link
            Mouse.Click(uIContinuetoNetBankingHyperlink, new Point(54, 6));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public UINetBankingInternetExWindow UINetBankingInternetExWindow
        {
            get
            {
                if ((this.mUINetBankingInternetExWindow == null))
                {
                    this.mUINetBankingInternetExWindow = new UINetBankingInternetExWindow();
                }
                return this.mUINetBankingInternetExWindow;
            }
        }
        
        public UIHDFCBankPersonalBankWindow UIHDFCBankPersonalBankWindow
        {
            get
            {
                if ((this.mUIHDFCBankPersonalBankWindow == null))
                {
                    this.mUIHDFCBankPersonalBankWindow = new UIHDFCBankPersonalBankWindow();
                }
                return this.mUIHDFCBankPersonalBankWindow;
            }
        }
        
        public UINetBankingInternetExWindow1 UINetBankingInternetExWindow1
        {
            get
            {
                if ((this.mUINetBankingInternetExWindow1 == null))
                {
                    this.mUINetBankingInternetExWindow1 = new UINetBankingInternetExWindow1();
                }
                return this.mUINetBankingInternetExWindow1;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private UINetBankingInternetExWindow mUINetBankingInternetExWindow;
        
        private UIHDFCBankPersonalBankWindow mUIHDFCBankPersonalBankWindow;
        
        private UINetBankingInternetExWindow1 mUINetBankingInternetExWindow1;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'https://www.hdfcbank.com/'
        /// </summary>
        public string UIHDFCBankPersonalBankWindowUrl = "https://www.hdfcbank.com/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'https://www.hdfcbank.com/'
        /// </summary>
        public string UIHDFCBankPersonalBankWindowUrl = "https://www.hdfcbank.com/";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UINetBankingInternetExWindow : BrowserWindow
    {
        
        public UINetBankingInternetExWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "NetBanking";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("NetBanking");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UINetBankingDocument UINetBankingDocument
        {
            get
            {
                if ((this.mUINetBankingDocument == null))
                {
                    this.mUINetBankingDocument = new UINetBankingDocument(this);
                }
                return this.mUINetBankingDocument;
            }
        }
        #endregion
        
        #region Fields
        private UINetBankingDocument mUINetBankingDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UINetBankingDocument : HtmlDocument
    {
        
        public UINetBankingDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "NetBanking";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/assets/popuppages/netbanking.htm";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.hdfcbank.com/assets/popuppages/netbanking.htm";
            this.WindowTitles.Add("NetBanking");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIContinuetoNetBankingHyperlink
        {
            get
            {
                if ((this.mUIContinuetoNetBankingHyperlink == null))
                {
                    this.mUIContinuetoNetBankingHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIContinuetoNetBankingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIContinuetoNetBankingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIContinuetoNetBankingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIContinuetoNetBankingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Continue to NetBanking";
                    this.mUIContinuetoNetBankingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/netbanking/";
                    this.mUIContinuetoNetBankingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIContinuetoNetBankingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://netbanking.hdfcbank.com/netbanking/";
                    this.mUIContinuetoNetBankingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn btn-default redBtn";
                    this.mUIContinuetoNetBankingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn btn-default redBtn\" href=\"htt";
                    this.mUIContinuetoNetBankingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "10";
                    this.mUIContinuetoNetBankingHyperlink.WindowTitles.Add("NetBanking");
                    #endregion
                }
                return this.mUIContinuetoNetBankingHyperlink;
            }
        }
        
        public UISlide1Pane UISlide1Pane
        {
            get
            {
                if ((this.mUISlide1Pane == null))
                {
                    this.mUISlide1Pane = new UISlide1Pane(this);
                }
                return this.mUISlide1Pane;
            }
        }
        
        public HtmlDiv UIContinuetoNetBankingPane
        {
            get
            {
                if ((this.mUIContinuetoNetBankingPane == null))
                {
                    this.mUIContinuetoNetBankingPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIContinuetoNetBankingPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIContinuetoNetBankingPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIContinuetoNetBankingPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Continue to NetBanking ";
                    this.mUIContinuetoNetBankingPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIContinuetoNetBankingPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "pdtb25 text-center";
                    this.mUIContinuetoNetBankingPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"pdtb25 text-center\"";
                    this.mUIContinuetoNetBankingPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "33";
                    this.mUIContinuetoNetBankingPane.WindowTitles.Add("NetBanking");
                    #endregion
                }
                return this.mUIContinuetoNetBankingPane;
            }
        }
        
        public HtmlDiv UIPreloaderPane
        {
            get
            {
                if ((this.mUIPreloaderPane == null))
                {
                    this.mUIPreloaderPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIPreloaderPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "preloader";
                    this.mUIPreloaderPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIPreloaderPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIPreloaderPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIPreloaderPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIPreloaderPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"preloader\" style=\"opacity: 0.238751;\"";
                    this.mUIPreloaderPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "1";
                    this.mUIPreloaderPane.WindowTitles.Add("NetBanking");
                    #endregion
                }
                return this.mUIPreloaderPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIContinuetoNetBankingHyperlink;
        
        private UISlide1Pane mUISlide1Pane;
        
        private HtmlDiv mUIContinuetoNetBankingPane;
        
        private HtmlDiv mUIPreloaderPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISlide1Pane : HtmlDiv
    {
        
        public UISlide1Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "slide1";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "rsContent";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"rsContent\" id=\"slide1\" style=\"transition:opacity 400ms ease-in-out; visibi" +
                "lity: visible; opacity: 1;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "16";
            this.WindowTitles.Add("NetBanking");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIAssetspopuppagesimagImage
        {
            get
            {
                if ((this.mUIAssetspopuppagesimagImage == null))
                {
                    this.mUIAssetspopuppagesimagImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIAssetspopuppagesimagImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIAssetspopuppagesimagImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIAssetspopuppagesimagImage.SearchProperties[HtmlImage.PropertyNames.Alt] = null;
                    this.mUIAssetspopuppagesimagImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/assets/popuppages/images/banner_4_desktop.jpg";
                    this.mUIAssetspopuppagesimagImage.FilterProperties[HtmlImage.PropertyNames.Src] = "https://www.hdfcbank.com/assets/popuppages/images/banner_4_desktop.jpg";
                    this.mUIAssetspopuppagesimagImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/netbanking/";
                    this.mUIAssetspopuppagesimagImage.FilterProperties[HtmlImage.PropertyNames.Href] = "https://netbanking.hdfcbank.com/netbanking/";
                    this.mUIAssetspopuppagesimagImage.FilterProperties[HtmlImage.PropertyNames.Class] = "vDesc";
                    this.mUIAssetspopuppagesimagImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "class=\"vDesc\" src=\"images/banner_4_deskt";
                    this.mUIAssetspopuppagesimagImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUIAssetspopuppagesimagImage.WindowTitles.Add("NetBanking");
                    #endregion
                }
                return this.mUIAssetspopuppagesimagImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIAssetspopuppagesimagImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHDFCBankPersonalBankWindow : BrowserWindow
    {
        
        public UIHDFCBankPersonalBankWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "HDFC Bank: Personal Banking Services";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("HDFC Bank: Personal Banking Services");
            this.WindowTitles.Add("MSN India | Hotmail, Outlook, Skype, news, photos & videos");
            this.WindowTitles.Add("https://www.hdfcbank.com/");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHDFCBankPersonalBankDocument UIHDFCBankPersonalBankDocument
        {
            get
            {
                if ((this.mUIHDFCBankPersonalBankDocument == null))
                {
                    this.mUIHDFCBankPersonalBankDocument = new UIHDFCBankPersonalBankDocument(this);
                }
                return this.mUIHDFCBankPersonalBankDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHDFCBankPersonalBankDocument mUIHDFCBankPersonalBankDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHDFCBankPersonalBankDocument : HtmlDocument
    {
        
        public UIHDFCBankPersonalBankDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "HDFC Bank: Personal Banking Services";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.hdfcbank.com/";
            this.WindowTitles.Add("HDFC Bank: Personal Banking Services");
            #endregion
        }
        
        #region Properties
        public UIElement2Pane UIElement2Pane
        {
            get
            {
                if ((this.mUIElement2Pane == null))
                {
                    this.mUIElement2Pane = new UIElement2Pane(this);
                }
                return this.mUIElement2Pane;
            }
        }
        
        public HtmlHyperlink UILoginHyperlink
        {
            get
            {
                if ((this.mUILoginHyperlink == null))
                {
                    this.mUILoginHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "loginsubmit";
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = ";";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:;";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "homeloginbtn";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"homeloginbtn\" id=\"loginsubmit\" hr";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "257";
                    this.mUILoginHyperlink.WindowTitles.Add("HDFC Bank: Personal Banking Services");
                    #endregion
                }
                return this.mUILoginHyperlink;
            }
        }
        
        public UICee_closeBtnPane UICee_closeBtnPane
        {
            get
            {
                if ((this.mUICee_closeBtnPane == null))
                {
                    this.mUICee_closeBtnPane = new UICee_closeBtnPane(this);
                }
                return this.mUICee_closeBtnPane;
            }
        }
        
        public HtmlHyperlink UILoginHyperlink1
        {
            get
            {
                if ((this.mUILoginHyperlink1 == null))
                {
                    this.mUILoginHyperlink1 = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILoginHyperlink1.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "loginsubmit";
                    this.mUILoginHyperlink1.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILoginHyperlink1.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILoginHyperlink1.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Login";
                    this.mUILoginHyperlink1.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = ";";
                    this.mUILoginHyperlink1.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILoginHyperlink1.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:;";
                    this.mUILoginHyperlink1.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "homeloginbtn";
                    this.mUILoginHyperlink1.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"homeloginbtn\" id=\"loginsubmit\" hr";
                    this.mUILoginHyperlink1.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "258";
                    this.mUILoginHyperlink1.WindowTitles.Add("HDFC Bank: Personal Banking Services");
                    #endregion
                }
                return this.mUILoginHyperlink1;
            }
        }
        
        public UIViz_iframe36255a186aFrame UIViz_iframe36255a186aFrame
        {
            get
            {
                if ((this.mUIViz_iframe36255a186aFrame == null))
                {
                    this.mUIViz_iframe36255a186aFrame = new UIViz_iframe36255a186aFrame(this);
                }
                return this.mUIViz_iframe36255a186aFrame;
            }
        }
        #endregion
        
        #region Fields
        private UIElement2Pane mUIElement2Pane;
        
        private HtmlHyperlink mUILoginHyperlink;
        
        private UICee_closeBtnPane mUICee_closeBtnPane;
        
        private HtmlHyperlink mUILoginHyperlink1;
        
        private UIViz_iframe36255a186aFrame mUIViz_iframe36255a186aFrame;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIElement2Pane : HtmlDiv
    {
        
        public UIElement2Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "element2";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "(function() { var protocol = location.pr";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"element2\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "191";
            this.WindowTitles.Add("HDFC Bank: Personal Banking Services");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UINetBankingNetBankingPane
        {
            get
            {
                if ((this.mUINetBankingNetBankingPane == null))
                {
                    this.mUINetBankingNetBankingPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUINetBankingNetBankingPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUINetBankingNetBankingPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUINetBankingNetBankingPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "NetBanking\r\n\r\nNetBanking\r\nPrepaid/ Forex";
                    this.mUINetBankingNetBankingPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUINetBankingNetBankingPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "loginwrap";
                    this.mUINetBankingNetBankingPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"loginwrap\"";
                    this.mUINetBankingNetBankingPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "261";
                    this.mUINetBankingNetBankingPane.WindowTitles.Add("HDFC Bank: Personal Banking Services");
                    #endregion
                }
                return this.mUINetBankingNetBankingPane;
            }
        }
        
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "homePageBanner-overlay";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"homePageBanner-overlay\" style=\"background: rgb(0, 0, 0); left: 0px; top: 0" +
                        "px; width: 100%; height: 100%; position: fixed; z-index: 1000000; opacity: 0.7;\"" +
                        "";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "276";
                    this.mUIItemPane.WindowTitles.Add("HDFC Bank: Personal Banking Services");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUINetBankingNetBankingPane;
        
        private HtmlDiv mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICee_closeBtnPane : HtmlDiv
    {
        
        public UICee_closeBtnPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "cee_closeBtn";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"cee_closeBtn\" style=\"top: -15px; right: 5px; text-indent: 0px; cursor: pointe" +
                "r; background-image: none;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "278";
            this.WindowTitles.Add("HDFC Bank: Personal Banking Services");
            #endregion
        }
        
        #region Properties
        public HtmlImage UICloseImage
        {
            get
            {
                if ((this.mUICloseImage == null))
                {
                    this.mUICloseImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUICloseImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUICloseImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUICloseImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Close";
                    this.mUICloseImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/assets/images/close.png";
                    this.mUICloseImage.FilterProperties[HtmlImage.PropertyNames.Src] = "https://www.hdfcbank.com/assets/images/close.png";
                    this.mUICloseImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUICloseImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=\"Close\" src=\"/assets/images/close.pn";
                    this.mUICloseImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUICloseImage.WindowTitles.Add("HDFC Bank: Personal Banking Services");
                    #endregion
                }
                return this.mUICloseImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUICloseImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIViz_iframe36255a186aFrame : HtmlIFrame
    {
        
        public UIViz_iframe36255a186aFrame(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "viz_iframe36255a186a98f16c5751c04d903ONR";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "width=\"373\" height=\"329\" id=\"viz_iframe3";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "2";
            this.WindowTitles.Add("HDFC Bank: Personal Banking Services");
            #endregion
        }
        
        #region Properties
        public UITemplate_Fadein_FadeDocument UITemplate_Fadein_FadeDocument
        {
            get
            {
                if ((this.mUITemplate_Fadein_FadeDocument == null))
                {
                    this.mUITemplate_Fadein_FadeDocument = new UITemplate_Fadein_FadeDocument(this);
                }
                return this.mUITemplate_Fadein_FadeDocument;
            }
        }
        #endregion
        
        #region Fields
        private UITemplate_Fadein_FadeDocument mUITemplate_Fadein_FadeDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITemplate_Fadein_FadeDocument : HtmlDocument
    {
        
        public UITemplate_Fadein_FadeDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Template_Fadein_Fadeout";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.hdfcbank.com/";
            this.WindowTitles.Add("HDFC Bank: Personal Banking Services");
            #endregion
        }
        
        #region Properties
        public UIApplyNowPane UIApplyNowPane
        {
            get
            {
                if ((this.mUIApplyNowPane == null))
                {
                    this.mUIApplyNowPane = new UIApplyNowPane(this);
                }
                return this.mUIApplyNowPane;
            }
        }
        #endregion
        
        #region Fields
        private UIApplyNowPane mUIApplyNowPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIApplyNowPane : HtmlDiv
    {
        
        public UIApplyNowPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "prd-item-list-2";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Apply Now";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "item-list";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"item-list\" id=\"prd-item-list-2\" style=\"z-index: 10;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "12";
            this.WindowTitles.Add("HDFC Bank: Personal Banking Services");
            #endregion
        }
        
        #region Properties
        public HtmlImage UISspIN_HDFC_DMP7f721cImage
        {
            get
            {
                if ((this.mUISspIN_HDFC_DMP7f721cImage == null))
                {
                    this.mUISspIN_HDFC_DMP7f721cImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUISspIN_HDFC_DMP7f721cImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUISspIN_HDFC_DMP7f721cImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUISspIN_HDFC_DMP7f721cImage.SearchProperties[HtmlImage.PropertyNames.Alt] = null;
                    this.mUISspIN_HDFC_DMP7f721cImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/ssp/IN_HDFC_DMP/7f721c89-42b5-4d90-8c5e-116d98b954e5.jpg";
                    this.mUISspIN_HDFC_DMP7f721cImage.FilterProperties[HtmlImage.PropertyNames.Src] = "https://cdn25.vizury.com/ssp/IN_HDFC_DMP/7f721c89-42b5-4d90-8c5e-116d98b954e5.jpg" +
                        "";
                    this.mUISspIN_HDFC_DMP7f721cImage.FilterProperties[HtmlImage.PropertyNames.Class] = "bannerimage";
                    this.mUISspIN_HDFC_DMP7f721cImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "class=\"bannerimage\" style=\"z-index: 7; o";
                    this.mUISspIN_HDFC_DMP7f721cImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUISspIN_HDFC_DMP7f721cImage.WindowTitles.Add("HDFC Bank: Personal Banking Services");
                    #endregion
                }
                return this.mUISspIN_HDFC_DMP7f721cImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUISspIN_HDFC_DMP7f721cImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UINetBankingInternetExWindow1 : BrowserWindow
    {
        
        public UINetBankingInternetExWindow1()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "NetBanking";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.FilterProperties["OrderOfInvocation"] = "3";
            this.WindowTitles.Add("NetBanking");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public WinTitleBar UINetBankingInternetExTitleBar
        {
            get
            {
                if ((this.mUINetBankingInternetExTitleBar == null))
                {
                    this.mUINetBankingInternetExTitleBar = new WinTitleBar(this);
                    #region Search Criteria
                    this.mUINetBankingInternetExTitleBar.WindowTitles.Add("NetBanking");
                    #endregion
                }
                return this.mUINetBankingInternetExTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private WinTitleBar mUINetBankingInternetExTitleBar;
        #endregion
    }
}
